### ISSUE TITLE
Possible leak with NVorbis.Ogg.Packet

### ISSUE THREAD

**Issue by TrevorSundberg** [ioctlLR/NVorbis#10]
I'm writing a game and I noticed the memory was slowly going up while sitting on a menu screen. I ran the built in VS profiler and took a memory snapshot, and then took another and noticed the number of NVorbis.Ogg.Packet increased since the last time. This consistently repros and will continue to increase as long as I play music. I'm using VorbisReader to read samples over time as to stream music. I would assume that the packets would be cleaned up after their samples are read.

When I looked into the implementation of PacketReader I believe 'Prev' is never being cleared for any packets, except in Dispose and in the case of the last packet being partial. 

If all this means is that a song will fully load by the time it gets to the end... it's not great but it's not the end of the world. At least I'm still only loading one song at a time and they unload when I change levels. My only major worry that I have yet to test is that the song is looping, and my current implementation for looping is to set the VorbisReader.DecodedPosition = 0; as well as the Stream.Position = 0; As long as that goes back and finds already read packets, I can live with this.

Thanks for writing such a great library regardless, love your work!

**Comment by ioctlLR** [comment]
NVorbis creates a Packet instance for each packet found in the file.  It does this one time per file as it reads the file.  So memory usage will climb until the whole file is read.  After that, memory usage should remain fixed, no matter how many loops are performed.

Looks like it is working as designed. :)

Sorry for taking so long to reply; been overwhelmed by real work.

**Comment by TrevorSundberg** [comment]
I disagree with this 'as designed' behavior. For example, take a file that is larger than the amount of remaining memory a computer has. This file should be able to be streamed, however with the behavior being exhibited here you cannot because it will crash as it nears the end of the file (or the limit of your memory).

**Comment by ioctlLR** [comment]
It works out to about 292KB per minute of audio on a 64-bit machine (based on a file I just had sitting around).  Add the overhead of buffers & such (WAG of 250KB) and a typical 4 minute file at 112Kbit should be about 1.4MB.  Not great, but certainly not the full 3.2MB of the file.

One change that I would entertain is to have the Packet instances dynamically created and only keep up with the page headers & indexes.  That's more complicated (especially for seeking), but would reduce the memory footprint to probably a couple dozen KB per minute...  The downside is that it would make performance go down a little since more logic would have to run in PeekNextPacket().  I'm hesitant to make such changes due to the performance already being so much lower than native.

**Comment by ioctlLR** [comment]
BTW, I added issue #13 for this.
