### ISSUE TITLE
InvalidDataException

### ISSUE THREAD

**Issue by DoubleCouponDay** [ioctlLR/NVorbis#22]
Attempting to read an ogg music file fails using VorbisWaveReader. It can be played perfectly using groove music or music bee. Here is [the music file in question](https://mega.nz/#!yF8w2A6C!ybYW5927ymodUGL-mNddDTgutOyKAC_gAPukxdcf9tQ). When I refresh the file by exporting from audacity, It is able to be played. What could be the underlying cause of this inside the file? how did it get like this?

I noticed in `OggPacketReader.cs line 131` the origin of this error. Can someone explain why that code path would be invoked? 

```  Message: 
    System.IO.InvalidDataException : Found invalid data while decoding.
  Stack Trace: 
    PacketReader.AddPacket(Packet packet)
    ContainerReader.AddPage(PageHeader hdr)
    ContainerReader.GatherNextPage()
    ContainerReader.GatherNextPage(Int32 streamSerial)
    PacketReader.PeekNextPacketInternal()
    PacketReader.GetNextPacket()
    VorbisStreamDecoder.TryInit()
    VorbisReader.NewStream(Object sender, NewStreamEventArgs ea)
    ContainerReader.GatherNextPage()
    ContainerReader.Init()
    VorbisReader.LoadContainer(IContainerReader containerReader)
    VorbisReader.ctor(Stream stream, Boolean closeStreamOnDispose)
    VorbisWaveReader.ctor(Stream sourceStream)
    universalogg.ctor(audiofile track) line 13
    audiodecoder.streamdecodedchunks(audiofile track) line 31
    when_an_audio_file_is_decoded.it_can_decode_corrupt_ogg() line 136
```

**Comment by ToddBertaOldham** [comment]
I’m not the creator of this library but from what I can see from the code it looks like the ogg file is either incomplete or was not properly written. However, that would be strange considering you exported from Audacity so maybe this is a bug. The line you posted shows that the reader reads a packet that is supposed to be a continuation of another packet, however that previous packet does not exist. Could you please upload the original file? I downloaded the file from the link, but it was an mp3 file. You can upload the file directly to this issue. I have seen that a lot of music players are tolerant of broken ogg files and will tend to just play what they have.

**Comment by DoubleCouponDay** [comment]
@ToddBertaOldham Just to clarify, I received this file from the internet and did not export it myself. reexporting the file using audacity's vorbis encoder fixes this error message.

 Here is the original file: https://mega.nz/#!yF8w2A6C!ybYW5927ymodUGL-mNddDTgutOyKAC_gAPukxdcf9tQ

**Comment by ToddBertaOldham** [comment]
Sorry I misread the part about Audacity. I opened the file in VLC to see if it logged anything about it being partially corrupted but there was nothing. 

I’m not quite sure how to make the reader more tolerant of this kind of issue. If I had to take a wild guess, I suppose it could just treat the packet as though it wasn’t a continuation of another packet if there wasn’t a last packet or the last packet isn’t continued. I’m not sure what the full effects of that would be or if that would really even fix the issue.

If I have some time, I can try to take a look at this. I don't want to rush into any major changes though considering I'm not the original author and you fixed the file with Audacity.

**Comment by DoubleCouponDay** [comment]
This is just a gut feeling but I was reexporting all the corrupted files today and noticed all of them had like 30 seconds of silence at the end. Could the compression of audio silence contribute to mishandled decompression? I'm not an expert in this but hope it helps.

**Comment by ioctlLR** [comment]
The original link is to an MP3 file.  NVorbis is not an MP3 decoder, and will always choke on an MP3 file.

My I recommend [NLayer](https://github.com/NAudio/NLayer), instead?

@ToddBertaOldham, maybe there should be a try/catch higher in that stack trace that says "this doesn't look like an Ogg Vorbis file" instead of allowing the InvalidDataException to bubble?

**Comment by DoubleCouponDay** [comment]
@ioctlLR If I was sending an mp3 file stream into the VorbisWaveReader, it would throw `InvalidDataException: Could not determine container type!`. Thats not whats happening here.

**Comment by ToddBertaOldham** [comment]
The file that is causing the issue is an Ogg Vorbis file that was downloaded from the internet. It throws the exception at this [line](https://github.com/ioctlLR/NVorbis/blob/master/NVorbis/Ogg/OggPacketReader.cs#L131). The Ogg file is fixed after being opened and then reexported as an Ogg file in Audacity. The very first link went to a site that converted the uploaded Ogg file to an MP3 without @DoubleCouponDay knowing. The second link posted contains the original corrupted file. Is that right or I am confused @DoubleCouponDay?

**Comment by DoubleCouponDay** [comment]
Yeah no big deal.

**Comment by ToddBertaOldham** [comment]
I just wanted to clarify everything. I’ll try to look at this soon. I’ll leave the issue open for now.

**Comment by ioctlLR** [comment]
My apologies, I failed to realize there was a later link to the actual problem file.  Oops!

How does audiodecoder.streamdecodedchunks(audiofile) work?  Any threading involved?  I ask because corrupted.ogg decoded fine for me.  Beautiful little piece of music, by the way.

I know you may not be able to share the actual code, but if you could give us a minimal reproduction of the issue, that would be enough.

**Comment by DoubleCouponDay** [comment]
I have an automated test that [you can read here](https://github.com/DoubleCouponDay/portfolio/blob/master/server/portfolio.tests/decoding.fs#L140). No multithreading in this specific context.

```
    [<Theory>]
    [<InlineData(corruptedoggpath, null)>]
    ///returns if the file is corrupt or not
    member public this.it_fails_to_decode_corrupted_ogg_file(virtualfilepath:string, ?stream: MemoryStream): Boolean =        
        let mutable didthrow = false

        try
            if stream.IsNone then
                use input = this.prepareencoding(virtualfilepath, oggextension)
                let output = context.streamdecodedchunks(input)  
                ()

            else
                use reader = new VorbisWaveReader(stream.Value)
                Assert.True(reader.CanRead = true)
                ()
            ()

        with 
        | :? InvalidDataException as error ->
            didthrow <- true
            
        | error ->
            failwith ("unexpected error: " + error.ToString())

        didthrow
```

The general gist of the test is to read the `corrupted.ogg` file into a stream, choose a decoder based on the file extension and pass the stream as argument to the constructor of `VorbisFileReader`, which relies on this libraries' `VorbisReader` type.

**Comment by DoubleCouponDay** [comment]
I've successfully reproduced this error in NVorbis version 0.8.4. When I the latest version of NVorbis, the file can be read. This is due to the fact that NAudio.Vorbis has a dependency of NVorbis >= 0.8.4 and it seems that this type of error was fixed somewhere in the two later versions.

**Comment by ioctlLR** [comment]
@ToddBertaOldham I'd think a new release (here and on Nuget) is in order.  That should quietly fix the issue without requiring an update to NAudio.Vorbis.

**Comment by ToddBertaOldham** [comment]
I'm a little confused. Shouldn't NAudio.Vorbis already be fixed from the last release? Regardless, I saw you made some changes so I'll publish a new release on Nuget and Github tonight.

**Comment by ioctlLR** [comment]
You're right.  NAudio.Vorbis needs a new release...  I'll check with the org owner to see if he is willing to do so.

Take a look at those changes to make sure you're good with them.  I removed the extraneous Stream buffering and applied a couple minor performance buffs.  In theory those are safe to do...

**Comment by ToddBertaOldham** [comment]
Okay I'll take a look at them and test some stuff and then post a new version if everything looks good.

**Comment by ToddBertaOldham** [comment]
I took a look through the code and tried to familiarize myself with it. I wanted to ask you about some of the changes before publishing. 

You said the stream buffering was extraneous, but it seemed like it was what provided support for streams without seeking. Am I wrong about this or is this a breaking change? Is it up to the user to provide that functionality when they need it now?

The other thing I saw was that the stream buffering seemed to provide at least some degree of thread safety. There doesn’t seem to be any replacement for it which would be a breaking change unless it was just unnecessary. Is it up to the user to provide this now as well?

I also wanted to talk about the version number. If breaking changes are made it might be good to follow semantic versioning. Is there any reason the library isn’t at 1.0.0 yet? I’d say it’s stable and out of prelease. It might be good to release 1.0.0 or at least bump from 0.8.6 to 0.9.0 if we are breaking anything.

The performance changes look good, but it seems that MichalX2002 now goes by TechnologicalPizza. At least that’s where I get redirected to. It’s not a big deal but I’ll probably update the credit.

**Comment by ioctlLR** [comment]
Well, it's only breaking if the code was working as-designed... ;)
The buffering was supposed to make multithreaded streaming possible, but it never worked right.  NVorbis has always been, um, "quirky" in multithreaded apps, even with the buffering.  And as we've seen, forward-only streams don't actually work.  The buffering code is really complicated, so the best answer is to remove it and have the caller provide the appropriate support.

0.9.0 seems like an appropriate version for the release.  Adding a readme.txt to the package probably also makes sense so we can explain the changes and how to work around them if there is an issue.  I don't want to go to 1.0.0 just yet; I'm working on one more major change first (lightweight Ogg container reader).

I'm fine with you updating the credits.  

Moving to net45 is necessary due to new types in use.  Given the age of net35, I highly recommend anyone still using it to move to net45 or even netstandard2.1/Core 3.0.

**Comment by ToddBertaOldham** [comment]
Great that all makes sense. I’ll include the changes in the release notes for the packages and publish the new release tonight.
